spring.application.name=cafeteria_unifranz

spring.datasource.url=jdbc:postgresql://localhost:5432/cafeteria_unifranz
spring.datasource.username=postgres
spring.datasource.password=pishi4017
spring.jpa.hibernate.ddl-auto=update