/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KioskoIndexRouteImport } from './routes/kiosko/index'
import { Route as KioskoConfirmacionRouteImport } from './routes/kiosko/confirmacion'
import { Route as KioskoLoginRouteImport } from './routes/kiosko/login'
import { Route as KioskoMenuRouteImport } from './routes/kiosko/menu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskoIndexRoute = KioskoIndexRouteImport.update({
  id: '/kiosko/',
  path: '/kiosko/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskoConfirmacionRoute = KioskoConfirmacionRouteImport.update({
  id: '/kiosko/confirmacion',
  path: '/kiosko/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskoLoginRoute = KioskoLoginRouteImport.update({
  id: '/kiosko/login',
  path: '/kiosko/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskoMenuRoute = KioskoMenuRouteImport.update({
  id: '/kiosko/menu',
  path: '/kiosko/menu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiosko/confirmacion': typeof KioskoConfirmacionRoute
  '/kiosko/login': typeof KioskoLoginRoute
  '/kiosko/menu': typeof KioskoMenuRoute
  '/kiosko/': typeof KioskoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosko/confirmacion': typeof KioskoConfirmacionRoute
  '/kiosko/login': typeof KioskoLoginRoute
  '/kiosko/menu': typeof KioskoMenuRoute
  '/kiosko': typeof KioskoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kiosko/confirmacion': typeof KioskoConfirmacionRoute
  '/kiosko/login': typeof KioskoLoginRoute
  '/kiosko/menu': typeof KioskoMenuRoute
  '/kiosko/': typeof KioskoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/kiosko/confirmacion' | '/kiosko/login' | '/kiosko/menu' | '/kiosko/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/kiosko/confirmacion' | '/kiosko/login' | '/kiosko/menu' | '/kiosko'
  id:
    | '__root__'
    | '/'
    | '/kiosko/confirmacion'
    | '/kiosko/login'
    | '/kiosko/menu'
    | '/kiosko/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KioskoConfirmacionRoute: typeof KioskoConfirmacionRoute
  KioskoLoginRoute: typeof KioskoLoginRoute
  KioskoMenuRoute: typeof KioskoMenuRoute
  KioskoIndexRoute: typeof KioskoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosko/': {
      id: '/kiosko/'
      path: '/kiosko'
      fullPath: '/kiosko/'
      preLoaderRoute: typeof KioskoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosko/confirmacion': {
      id: '/kiosko/confirmacion'
      path: '/kiosko/confirmacion'
      fullPath: '/kiosko/confirmacion'
      preLoaderRoute: typeof KioskoConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosko/login': {
      id: '/kiosko/login'
      path: '/kiosko/login'
      fullPath: '/kiosko/login'
      preLoaderRoute: typeof KioskoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosko/menu': {
      id: '/kiosko/menu'
      path: '/kiosko/menu'
      fullPath: '/kiosko/menu'
      preLoaderRoute: typeof KioskoMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KioskoConfirmacionRoute: KioskoConfirmacionRoute,
  KioskoLoginRoute: KioskoLoginRoute,
  KioskoMenuRoute: KioskoMenuRoute,
  KioskoIndexRoute: KioskoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
